import {useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight,ArrowRight,Check,Eye,ShieldCheck,FileSpreadsheet,Plus,Minus} from 'lucide-react';
import {salesDetails as copy} from './salesContent';
import WaitlistForm from './WaitlistForm';
export default function SalesDetails(){const[open,setOpen]=useState<number|null>(0);
 return <><section className="sales-proof" id="why"><div className="sales-proof-inner"><div><span className="eyebrow">YOUR DASHBOARD SHOULD ANSWER BACK.</span><h2>{copy.proofTitle}</h2><p>{copy.proofBody}</p><Link to="/dashboard" className="button lime">{copy.proofCta}<ArrowUpRight size={17}/></Link></div><div className="proof-receipt"><div className="receipt-heading"><Eye size={20}/><strong>Cash collected</strong><span>VERIFIED FROM ROWS</span></div><strong className="receipt-amount">$8,250<span>Illustrative example</span></strong><div className="receipt-formula">Successful payments <b>−</b> refunds <b>=</b> collected cash</div><div className="receipt-row"><span>Stripe · Payment 001</span><strong>$6,000</strong><Check size={15}/></div><div className="receipt-row"><span>PayPal · Payment 002</span><strong>$2,500</strong><Check size={15}/></div><div className="receipt-row"><span>Stripe · Refund 003</span><strong>−$250</strong><Check size={15}/></div><div className="receipt-end"><FileSpreadsheet size={16}/> The exact records. Ready to export.</div></div></div></section>
 <section className="sales-section sales-outcomes"><div className="sales-section-heading"><div><span className="eyebrow">{copy.outcomesEyebrow}</span><h2>{copy.outcomesTitle}</h2></div><p>{copy.outcomesIntro}</p></div><div className="outcome-grid">{copy.outcomes.map((o,i)=><article key={o.title}><span className="outcome-number">0{i+1}</span><h3>{o.title}</h3><p>{o.body}</p><span className="outcome-question">{o.question}<ArrowUpRight size={17}/></span></article>)}</div></section>
 <section className="sales-community"><div><span className="eyebrow">THE JUDGMENT. AND THE TOOL.</span><h2>{copy.communityTitle}</h2><p>{copy.communityBody}</p><div className="community-pair"><div><span>MAKE DATA SEXY</span><strong>{copy.community[0].title}</strong><p>{copy.community[0].body}</p></div><span>+</span><div><span>NOBLINDSPOTS</span><strong>{copy.community[1].title}</strong><p>{copy.community[1].body}</p></div></div><a href="#early-access" className="text-link">{copy.communityCta}<ArrowRight size={17}/></a></div><aside><span className="quote-mark">“</span><blockquote>{copy.founderQuote}</blockquote><div><span className="founder-initials">MB</span><p><strong>{copy.founderName}</strong><span>Builder of NoBlindSpots · Make Data Sexy</span></p></div></aside></section>
 <section className="sales-section sales-faq"><div><span className="eyebrow">A FEW STRAIGHT ANSWERS</span><h2>{copy.faqTitle}</h2></div><div>{copy.faq.map((f,i)=><article key={f.q}><button aria-expanded={open===i} aria-controls={'faq-'+i} onClick={()=>setOpen(open===i?null:i)}>{f.q}{open===i?<Minus size={18}/>:<Plus size={18}/>}</button>{open===i&&<p id={'faq-'+i}>{f.a}</p>}</article>)}</div></section>
 <section className="sales-access" id="early-access"><div><span className="eyebrow"><span className="status-dot"/> REQUEST EARLY ACCESS</span><h2>{copy.accessTitle}</h2><p>{copy.accessBody}</p><ul>{copy.accessPoints.map(p=><li key={p}><Check size={17}/>{p}</li>)}</ul><span className="access-note"><ShieldCheck size={17}/>{copy.accessNote}</span></div><WaitlistForm/></section></>;
}