import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {handleApi} from '../server/worker.ts';
function database(){const db=new DatabaseSync(':memory:');for(const path of readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())db.exec(readFileSync('drizzle/'+path,'utf8'));return db;}
function adapter(db){return {prepare(sql){let values=[];return{bind(...args){values=args;return this},async first(){return db.prepare(sql).get(...values)||null},async all(){return{results:db.prepare(sql).all(...values)}},async run(){return db.prepare(sql).run(...values)}}},async batch(statements){db.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());db.exec('COMMIT');return results}catch(e){db.exec('ROLLBACK');throw e}}};}
async function request(env,path,{actor='owner-a',mode='live',method='GET',body,origin}={}){const headers={'content-type':'application/json','x-nbs-workspace':mode};if(actor)headers['oai-authenticated-user-id']=actor;if(origin)headers.origin=origin;const r=await handleApi(new Request('https://app.example/api'+path,{method,headers,...(body?{body:JSON.stringify(body)}:{})}),env);return{status:r.status,body:await r.json()};}
const payload={kind:'transactions',source:'stripe',filename:'payments.csv',csv:'id,date,name,email,amount,status\npay_1,2026-09-01,Alex,alex@example.com,100,succeeded',mapping:{source_id:'id',occurred_at:'date',name:'name',email:'email',amount:'amount',status:'status'}};
test('API rejects anonymous access and cross-origin mutation',async()=>{const db=database(),env={DB:adapter(db)};assert.equal((await request(env,'/data',{actor:null})).status,401);assert.equal((await request(env,'/init',{method:'POST',body:{},origin:'https://evil.example'})).status,403);db.close();});
test('Repeat imports upsert, unmatched money survives, and excluded rows remain excluded on re-import',async()=>{const db=database(),env={DB:adapter(db)};await request(env,'/init',{method:'POST',body:{}});const first=await request(env,'/import',{method:'POST',body:payload});assert.equal(first.status,200);assert.equal(first.body.run.inserted,1);const second=await request(env,'/import',{method:'POST',body:payload});assert.equal(second.body.run.updated,1);const data=(await request(env,'/data')).body.records;assert.equal(data.length,1);assert.equal(data[0].amount,10000);assert.equal(data[0].contact_id,'');await request(env,'/reconcile',{method:'POST',body:{id:data[0].id,action:'exclude',reason:'Duplicate source'}});await request(env,'/import',{method:'POST',body:payload});assert.equal((await request(env,'/data')).body.records[0].excluded,true);db.close();});
test('Invalid imports never save valid subsets; rejection is observable',async()=>{const db=database(),env={DB:adapter(db)};await request(env,'/init',{method:'POST',body:{}});const bad={...payload,csv:payload.csv+'\npay_2,not-a-date,Alex,alex@example.com,20,succeeded'};assert.equal((await request(env,'/import',{method:'POST',body:bad})).status,422);assert.equal((await request(env,'/data')).body.records.length,0);assert.equal((await request(env,'/runs')).body[0].status,'rejected');db.close();});
test('Tenant isolation covers reads and record matching/exclusion',async()=>{const db=database(),env={DB:adapter(db)};await request(env,'/init',{method:'POST',body:{}});await request(env,'/init',{actor:'owner-b',method:'POST',body:{}});await request(env,'/import',{method:'POST',body:payload});const id=(await request(env,'/data')).body.records[0].id;assert.equal((await request(env,'/data',{actor:'owner-b'})).body.records.length,0);assert.equal((await request(env,'/reconcile',{actor:'owner-b',method:'POST',body:{id,action:'exclude',reason:'Other tenant'}})).status,404);db.close();});
test('Contact backfill matches previous payments and a manual match survives re-import',async()=>{const db=database(),env={DB:adapter(db)};await request(env,'/init',{method:'POST',body:{}});await request(env,'/import',{method:'POST',body:payload});await request(env,'/import',{method:'POST',body:{kind:'contacts',source:'ghl',csv:'id,date,name,email\nc1,2026-09-01,Alex,alex@example.com',mapping:{source_id:'id',occurred_at:'date',name:'name',email:'email'}}});let rows=(await request(env,'/data')).body.records;const contact=rows.find(r=>r.kind==='contacts'),tx=rows.find(r=>r.kind==='transactions');assert.equal(tx.data.match_confidence,'email');await request(env,'/reconcile',{method:'POST',body:{id:tx.id,action:'match',contactId:contact.id}});await request(env,'/import',{method:'POST',body:payload});rows=(await request(env,'/data')).body.records;assert.equal(rows.find(r=>r.kind==='transactions').data.match_confidence,'manual');db.close();});
test('Sample and real workspaces are separate and team reports persist',async()=>{const db=database(),env={DB:adapter(db)};await request(env,'/init',{method:'POST',body:{}});await request(env,'/init',{mode:'demo',method:'POST',body:{}});assert.ok((await request(env,'/data',{mode:'demo'})).body.records.length>100);assert.equal((await request(env,'/data')).body.records.length,0);let r=await request(env,'/submissions',{method:'POST',body:{user_id:'owner-a',submission_date:'2026-09-07',submission_type:'closer',data:{cashCollected:100}}});assert.equal(r.status,200);r=await request(env,'/submissions');assert.equal(r.body[0].data.cashCollected,100);db.close();});
test('Workspace identity and owner role cannot be supplied by client JSON',async()=>{const db=database(),env={DB:adapter(db)};await request(env,'/init',{method:'POST',body:{org:'owner-b:live',role:'admin'}});const session=await request(env,'/session');assert.equal(session.body.user.id,'owner-a');assert.equal((await request(env,'/users',{method:'POST',body:{id:'owner-a',name:'A',email:'a@example.com',role:'closer'}})).status,400);db.close();});
