import {useState} from 'react';
import {CalendarDays,Download,ArrowUpRight} from 'lucide-react';
import {type SavedRecord,downloadRows,dateRange} from '../../lib/useWorkspace';
import {formatExact,type DataRecord} from '../../lib/engine';
import Modal from './Modal';
export function useFilters(records:SavedRecord[]=[]){
 const[period,setPeriod]=useState('30'),[offer,setOffer]=useState('all'),[custom,setCustom]=useState(dateRange('30'));
 const range=period==='custom'?custom:dateRange(period);
 const active=records.filter(r=>!r.excluded&&r.occurred_at>=range.from&&r.occurred_at<=range.to&&(offer==='all'||(r.offer||'Unallocated')===offer));
 return{period,setPeriod,offer,setOffer,range,custom,setCustom,active,offers:[...new Set(records.map(r=>r.offer).filter(Boolean))].sort()};
}
export function FilterBar({filters}:{filters:ReturnType<typeof useFilters>}){
 return <div className="filter-bar"><div className="filter-context"><CalendarDays size={17}/><span>{new Date(filters.range.from+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})} – {new Date(filters.range.to+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</span></div><div className="filter-inputs"><label className="sr-only" htmlFor="period">Date range</label><select id="period" value={filters.period} onChange={e=>filters.setPeriod(e.target.value)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="month">This month</option><option value="custom">Custom dates</option></select>{filters.period==='custom'&&<><input aria-label="Start date" type="date" value={filters.custom.from} max={filters.custom.to} onChange={e=>filters.setCustom({...filters.custom,from:e.target.value})}/><input aria-label="End date" type="date" value={filters.custom.to} min={filters.custom.from} onChange={e=>filters.setCustom({...filters.custom,to:e.target.value})}/></>}<label className="sr-only" htmlFor="offer-filter">Offer</label><select id="offer-filter" value={filters.offer} onChange={e=>filters.setOffer(e.target.value)}><option value="all">All offers</option>{filters.offers.map(o=><option key={o}>{o}</option>)}</select></div></div>
}
export function MetricTile({label,value,note,onClick,accent=false}:{label:string;value:string;note:string;onClick:()=>void;accent?:boolean}){return <button className={'metric-tile '+(accent?'accent':'')} onClick={onClick}><span className="metric-label">{label}<ArrowUpRight size={17}/></span><strong>{value}</strong><span className="metric-note">{note}</span></button>}
export function RecordTable({rows}:{rows:(DataRecord&{id?:string})[]}){return <div className="table-scroll"><table className="data-table"><thead><tr><th>Record / customer</th><th>Source</th><th>Date</th><th>Offer</th><th>Status</th><th className="number">Amount</th></tr></thead><tbody>{rows.slice(0,250).map((r,i)=><tr key={r.id||r.source+r.source_id+i}><td><strong>{r.name||r.email||r.source_id}</strong><small>{r.source_id}</small><details className="source-details"><summary>Original fields</summary><dl>{Object.entries(r.data).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{String(v)}</dd></div>)}</dl></details></td><td>{r.source}</td><td>{r.occurred_at}</td><td>{r.offer||'Unallocated'}</td><td><span className={'badge '+(['failed','no_show','lost'].includes(r.status)?'warning':'neutral')}>{r.status||r.kind}</span></td><td className="number">{formatExact(r.amount)}</td></tr>)}</tbody></table>{!rows.length&&<div className="empty-state"><h3>No records in this period</h3><p>Choose a wider date range or import your source data.</p></div>}{rows.length>250&&<p className="table-note">Showing 250 of {rows.length} records. Export for the full list.</p>}</div>}
export function Verification({title,description,rows,onClose}:{title:string;description:string;rows:DataRecord[];onClose:()=>void}){return <Modal title={title} onClose={onClose} wide><div className="verify-info"><span className="eyebrow">VERIFY THIS NUMBER</span><p>{description}</p><div><span>{rows.length} source records · USD</span><button className="button white" onClick={()=>downloadRows(rows.map(({data,...r})=>({...r,original_fields:JSON.stringify(data)})))}><Download size={16}/>Export source rows</button></div></div><RecordTable rows={rows}/></Modal>}
export function LoadState({loading,error,retry}:{loading:boolean;error:string;retry:()=>void}){return error?<div role="alert" className="empty-state"><h3>We couldn’t load this workspace.</h3><p>{error}</p><button className="button dark" onClick={retry}>Try again</button></div>:loading?<div className="loading-state" role="status"><span/>Loading your numbers…</div>:null;}
