import {NavLink,Link} from 'react-router-dom';
import {Eye,LayoutDashboard,GitMerge,UploadCloud,Layers,Wallet,Users,FileText,Target,Settings,ArrowUpRight,Activity,LogOut,HeartHandshake,Compass} from 'lucide-react';
import {useAuth} from '../../context/AuthContext';
export default function Sidebar({onNavigate}:{onNavigate?:()=>void}){
 const{user,mode,switchWorkspace,logout}=useAuth();
 const primary=[['/dashboard','Overview',LayoutDashboard],['/attribution','Attribution',Compass],['/pipeline','Sales pipeline',Layers],['/financials','Revenue & margin',Wallet],['/clients','Client success',HeartHandshake]] as const;
 const data=[['/imports','Data sources',UploadCloud],['/reconciliation','Reconciliation',GitMerge],['/activity','Import history',Activity]] as const;
 const team=[['/eod-form','Daily check-in',FileText],['/team-goals','Team goals',Target],['/admin/users','Team roster',Users],['/admin/settings','Settings',Settings]] as const;
 const group=(label:string,items:readonly(readonly[string,string,any])[])=><div className="nav-group"><p>{label}</p>{items.map(([path,title,Icon])=><NavLink key={path} to={path} onClick={onNavigate} className={({isActive})=>'nav-item '+(isActive?'active':'')}><Icon size={18}/><span>{title}</span>{path==='/reconciliation'&&<span className="nav-indicator"/>}</NavLink>)}</div>;
 return <aside className="app-sidebar"><Link to="/dashboard" className="brand sidebar-brand"><span className="brand-symbol"><Eye size={21}/></span>NoBlindSpots<span className="brand-dot">.</span></Link><div className="workspace-picker"><span className="workspace-avatar">{mode==='demo'?'N':'M'}</span><label><span>WORKSPACE</span><select aria-label="Choose workspace" value={mode} onChange={e=>void switchWorkspace(e.target.value as 'demo'|'live')}><option value="demo">Northstar · Sample</option><option value="live">My business</option></select></label></div><nav>{group('BUSINESS',primary)}{group('YOUR DATA',data)}{group('TEAM & WORKSPACE',team.filter(item=>user?.role==='admin'||!item[0].startsWith('/admin')))}</nav><div className="sidebar-bottom"><Link to="/" className="nav-item"><ArrowUpRight size={17}/> Visit sales page</Link><div className="account-row"><span className="account-avatar">{user?.name?.slice(0,1)||'M'}</span><div><strong>{user?.name||'Workspace owner'}</strong><small>Workspace owner</small></div><button aria-label="Sign out" onClick={logout}><LogOut size={17}/></button></div></div></aside>;
}