import {useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight,ArrowRight,GitMerge,ShieldCheck,TrendingDown,Wallet,CheckCircle2} from 'lucide-react';
import {ResponsiveContainer,ComposedChart,Area,Line,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts';
import Layout from '../components/Layout/Layout';
import {useWorkspace,downloadRows} from '../lib/useWorkspace';
import {summarize,formatMoney,formatExact,economics} from '../lib/engine';
import {useFilters,FilterBar,MetricTile,Verification,LoadState} from '../components/Workspace/Controls';
export default function Dashboard(){
 const{data,error,loading,refresh}=useWorkspace(),filters=useFilters(data?.records),[verify,setVerify]=useState<string|null>(null);
 const stats=useMemo(()=>{const value=summarize(filters.active);const period=(data?.records||[]).filter(r=>!r.excluded&&r.occurred_at>=filters.range.from&&r.occurred_at<=filters.range.to);value.offers=economics(period).filter(o=>filters.offer==='all'||o.offer===filters.offer);value.margin=value.offers.reduce((n,o)=>n+o.margin,0);value.marginPct=value.cash>0?value.margin/value.cash*100:null;return value;},[filters.active,data,filters.range.from,filters.range.to,filters.offer]);
 const chart=useMemo(()=>{const days=new Map<string,{date:string;cash:number;contracted:number}>();for(const r of filters.active){if(!['transactions','opportunities'].includes(r.kind))continue;const item=days.get(r.occurred_at)||{date:r.occurred_at,cash:0,contracted:0};if(r.kind==='transactions'&&['succeeded','refunded'].includes(r.status))item.cash+=r.amount/100;if(r.kind==='opportunities'&&r.status==='won')item.contracted+=r.amount/100;days.set(r.occurred_at,item);}let cash=0,contracted=0;return [...days.values()].sort((a,b)=>a.date.localeCompare(b.date)).map(r=>({...r,cash:cash+=r.cash,contracted:contracted+=r.contracted}));},[filters.active]);
 const definitions:Record<string,{description:string;rows:typeof filters.active}>={
 'Cash collected':{description:'Sum of successful payments plus negative refund records, in the selected period and offer. Processing fees are deducted separately in the margin calculation. Failed, pending, and excluded records do not count.',rows:filters.active.filter(r=>r.kind==='transactions'&&['succeeded','refunded'].includes(r.status))},
 'Contracted revenue':{description:'Total contract value of opportunities marked won in this period. This is a sales activity measure, not cash or a receivables balance.',rows:filters.active.filter(r=>r.kind==='opportunities'&&r.status==='won')},
 'Contribution margin':{description:'Collected cash minus ad spend, commissions, processing fees, direct expenses, and allocated overhead. Missing cost imports can overstate margin. Overhead is allocated in proportion to offer cash collections.',rows:filters.active.filter(r=>['transactions','ad_spend','commissions','expenses'].includes(r.kind))},
 'Show rate':{description:'Attended appointments divided by attended appointments plus no-shows. Cancelled, rescheduled, and future booked calls are excluded from the denominator.',rows:filters.active.filter(r=>r.kind==='appointments'&&['showed','no_show'].includes(r.status))}
 };
 return <Layout title="Business overview" subtitle={data?.settings.companyName?data.settings.companyName+' · Your numbers, with nothing swept under the rug.':'Your numbers, with nothing swept under the rug.'} showExport onExport={()=>downloadRows(filters.active.map(({data,...r})=>({...r,original_fields:JSON.stringify(data)})))}><LoadState loading={loading} error={error} retry={()=>void refresh()}/>{data&&!error&&<><div className="view-tabs"><span className="active">Executive view</span><Link to="/team-performance">Sales team <ArrowUpRight size={14}/></Link></div><FilterBar filters={filters}/>
 <div className="metric-grid"><MetricTile label="Cash collected" value={formatMoney(stats.cash)} note="Actual payments · net of refunds" onClick={()=>setVerify('Cash collected')} accent/><MetricTile label="Contracted revenue" value={formatMoney(stats.contracted)} note="Won contract value · not cash" onClick={()=>setVerify('Contracted revenue')}/><MetricTile label="Contribution margin" value={formatMoney(stats.margin)} note={(stats.marginPct===null?'No collected cash':stats.marginPct.toFixed(1)+'% of collected cash')+' · based on imported costs'} onClick={()=>setVerify('Contribution margin')}/><MetricTile label="Show rate" value={stats.showRate===null?'—':stats.showRate.toFixed(1)+'%'} note={stats.showed+' attended · '+stats.booked+' eligible bookings'} onClick={()=>setVerify('Show rate')}/></div>
 <div className="target-line"><span>Monthly cash target</span><strong>{formatMoney((data.records||[]).filter(r=>!r.excluded&&r.kind==='transactions'&&['succeeded','refunded'].includes(r.status)&&r.occurred_at.slice(0,7)===new Date().toISOString().slice(0,7)).reduce((n,r)=>n+r.amount,0))} / {formatMoney(data.settings.monthlyTarget)}</strong><Link to="/admin/settings">Adjust target <ArrowUpRight size={13}/></Link></div><div className="section-heading"><h2>Know where to look next.</h2><span>From the records in this period</span></div><div className="attention-grid"><Link to="/reconciliation" className="attention-card amber"><GitMerge size={20}/><div><strong>{stats.unmatched.length?stats.unmatched.length+' payments need a customer':'Payments are matched'}</strong><p>{stats.unmatched.length?'Complete the picture before trusting attribution.':'Every payment in this period has a contact.'}</p></div><ArrowUpRight size={18}/></Link><Link to="/reconciliation?tab=failed" className="attention-card"><Wallet size={20}/><div><strong>{stats.failed.length?formatMoney(stats.failed.reduce((s,r)=>s+r.amount,0))+' in failed payments':'No failed payments found'}</strong><p>{stats.failed.length?'Review these payments with your processor.':'Based on the records you’ve imported.'}</p></div><ArrowUpRight size={18}/></Link><Link to="/financials" className="attention-card"><TrendingDown size={20}/><div><strong>Look past top-line revenue.</strong><p>Compare what your offers earn after costs.</p></div><ArrowUpRight size={18}/></Link></div>
 <div className="dashboard-columns"><section className="panel chart-panel"><div className="panel-heading"><div><span className="eyebrow">REVENUE VISIBILITY</span><h2>Booked on paper. Collected in cash.</h2></div><button aria-label="View revenue records" onClick={()=>setVerify('Cash collected')}><ArrowUpRight size={19}/></button></div><div className="revenue-legend"><span><i/> Cash collected</span><span><i/> Contracted revenue</span><small>Cumulative in period</small></div>{chart.length?<div className="revenue-chart"><ResponsiveContainer width="100%" height={270}><ComposedChart data={chart} margin={{top:12,right:12,bottom:5,left:0}}><defs><linearGradient id="cash-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#b6d9b0" stopOpacity={.45}/><stop offset="1" stopColor="#b6d9b0" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e6ebe5" strokeDasharray="3 4"/><XAxis dataKey="date" tickFormatter={s=>new Date(s+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})} minTickGap={35} tickLine={false} axisLine={false} tick={{fontSize:12,fill:'#718078'}}/><YAxis tickFormatter={n=>'$'+(n/1000).toFixed(0)+'k'} tickLine={false} axisLine={false} tick={{fontSize:12,fill:'#718078'}} width={57}/><Tooltip formatter={(v:number,name:string)=>[formatExact(v*100),name==='cash'?'Collected':'Contracted']} contentStyle={{borderRadius:10,borderColor:'#dce3dd'}}/><Area type="monotone" dataKey="cash" stroke="#245e45" strokeWidth={3} fill="url(#cash-fill)"/><Line type="monotone" dataKey="contracted" stroke="#9daaa1" strokeWidth={2} strokeDasharray="5 5" dot={false}/></ComposedChart></ResponsiveContainer></div>:<div className="empty-state"><h3>Your money story starts with an import.</h3><Link to="/imports" className="button dark">Bring your data <ArrowRight size={16}/></Link></div>}<p className="chart-note">The two lines describe different events. Their difference is not an accounts receivable balance.</p></section>
 <section className="panel trust-panel"><div className="panel-heading"><div><span className="eyebrow">TRUST, WITH RECEIPTS</span><h2>Your data coverage</h2></div><ShieldCheck size={20}/></div>{['contacts','transactions','appointments','opportunities','expenses','ad_spend','commissions'].map(k=>{const n=filters.active.filter(r=>r.kind===k).length;return <div className="coverage-row" key={k}><span className={n?'coverage-check':'coverage-missing'}>{n?<CheckCircle2 size={15}/>:<span>—</span>}</span><span>{({contacts:'Contacts',transactions:'Payments',appointments:'Appointments',opportunities:'Pipeline',expenses:'Expenses',ad_spend:'Ad spend',commissions:'Commissions'} as Record<string,string>)[k]}</span><strong>{n?n.toLocaleString():'Not imported'}</strong></div>})}<Link className="trust-link" to="/imports">Manage data sources <ArrowRight size={16}/></Link></section></div>
 <section className="panel"><div className="panel-heading"><div><span className="eyebrow">OFFER ECONOMICS</span><h2>What actually stays in the business.</h2></div><Link className="text-link" to="/financials">Full breakdown <ArrowUpRight size={16}/></Link></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Offer</th><th className="number">Collected</th><th className="number">Costs</th><th className="number">Contribution</th><th>Margin</th></tr></thead><tbody>{stats.offers.map(o=><tr key={o.offer}><td><Link to="/financials"><strong>{o.offer}</strong></Link></td><td className="number">{formatMoney(o.cash)}</td><td className="number muted">{formatMoney(o.cash-o.margin)}</td><td className="number"><strong>{formatMoney(o.margin)}</strong></td><td><div className="margin-cell"><span className={'badge '+(o.marginPct!==null&&o.marginPct<30?'warning':'success')}>{o.marginPct===null?'—':o.marginPct.toFixed(1)+'%'}</span><span className="margin-track"><i style={{width:Math.max(0,Math.min(100,o.marginPct||0))+'%'}}/></span></div></td></tr>)}</tbody></table>{!stats.offers.length&&<p className="table-note">Import payments and offer costs to see this breakdown.</p>}</div></section></>}{verify&&<Verification title={verify} {...definitions[verify]} onClose={()=>setVerify(null)}/>}</Layout>;
}