import {useState,useRef} from 'react';
import {UploadCloud,ArrowRight,CheckCircle2,FileSpreadsheet,ArrowUpRight,Download,AlertTriangle} from 'lucide-react';
import {Link} from 'react-router-dom';
import Layout from '../components/Layout/Layout';
import {parseCSV,suggestMapping,normalizeImport,kinds,fields,labels,type Kind} from '../lib/engine';
import {post} from '../lib/api';
import {useWorkspace,downloadRows} from '../lib/useWorkspace';
import {RecordTable} from '../components/Workspace/Controls';
const sources=[['ghl','GoHighLevel','Contacts, appointments & pipeline'],['stripe','Stripe','Payments, fees & refunds'],['quickbooks','QuickBooks','Expenses & overhead'],['meta_ads','Meta ads','Campaign spend'],['paypal','PayPal','Payments outside your CRM'],['manual','Other / manual','Any source with a CSV export']];
export default function Imports(){
 const{data,refresh}=useWorkspace(),[source,setSource]=useState('ghl'),[kind,setKind]=useState<Kind>('contacts'),[filename,setFilename]=useState(''),[csv,setCsv]=useState(''),[parsed,setParsed]=useState<ReturnType<typeof parseCSV>|null>(null),[mapping,setMapping]=useState<Record<string,string>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null);
 const input=useRef<HTMLInputElement>(null);
 const preview=parsed?normalizeImport(parsed.headers,parsed.rows,mapping,kind,source):null;
 const chooseFile=async(file?:File)=>{if(!file)return;setError('');setResult(null);if(file.size>1000000){setError('Upload a CSV under 1 MB.');return;}try{const text=await file.text(),p=parseCSV(text);setCsv(text);setParsed(p);setMapping(suggestMapping(p.headers));setFilename(file.name);}catch(e){setError(e instanceof Error?e.message:'Could not read that file.');}};
 const save=async()=>{setBusy(true);setError('');try{const response=await post('/import',{source,kind,filename,csv,mapping});setResult(response.run);setParsed(null);setCsv('');await refresh();}catch(e){setError(e instanceof Error?e.message:'Import failed.');}finally{setBusy(false);}};
 const sample=()=>{const d=new Date().toISOString().slice(0,10);downloadRows(kind==='contacts'?[{source_id:'contact_001',occurred_at:d,name:'Example customer',email:'customer@example.com',channel:'Referral',offer:'Accelerator'}]:[{source_id:kind+'_001',occurred_at:d,name:'Example customer',email:'customer@example.com',contact_ref:'contact_001',offer:'Accelerator',status:kind==='transactions'?'succeeded':kind==='appointments'?'showed':kind==='opportunities'?'won':'active',amount:'1500.00',fees:kind==='transactions'?'45.00':'0.00',currency:'USD',category:kind==='expenses'?'delivery':''}],'noblindspots-'+kind+'-template.csv');};
 return <Layout title="Data sources" subtitle="Bring every part of the business into the same picture."><div className="section-heading"><h2>Start with the history. Keep the source.</h2><Link className="text-link" to="/activity">Import history <ArrowUpRight size={15}/></Link></div><div className="source-grid">{sources.map(([id,name,description])=>{const count=data?.records.filter(r=>r.source===id&&!r.excluded).length||0;return <button key={id} className={'source-card '+(source===id?'selected':'')} onClick={()=>{setSource(id);setResult(null);if(id==='stripe'||id==='paypal')setKind('transactions');else if(id==='quickbooks')setKind('expenses');else if(id==='meta_ads')setKind('ad_spend');}}><span className={'source-logo source-'+id}>{id==='stripe'?'S':id==='ghl'?'↗':id==='quickbooks'?'qb':id==='paypal'?'P':id==='meta_ads'?'∞':<FileSpreadsheet size={23}/>}</span><strong>{name}</strong><p>{description}</p><span className="source-status">{count?<><CheckCircle2 size={13}/>{count} records imported</>:<>CSV import available</>}</span></button>})}</div>
 <section className="panel import-panel"><div className="panel-heading"><div><span className="eyebrow">IMPORT YOUR DATA</span><h2>{parsed?'Map, review, then import.':'A better use for that CSV.'}</h2></div><span className="badge neutral">USD · Up to 500 rows / file</span></div><div className="import-type-row"><label>Record type<select value={kind} onChange={e=>setKind(e.target.value as Kind)}>{kinds.map(k=><option key={k} value={k}>{k.replace(/_/g,' ')}</option>)}</select></label><button className="text-link" onClick={sample}><Download size={16}/> Download a template</button></div>{error&&<div className="notice warning" role="alert"><AlertTriangle size={18}/>{error}</div>}{result&&<div className="import-success" role="status"><CheckCircle2 size={28}/><div><h3>Import complete. The picture is clearer.</h3><p>{result.inserted} new records · {result.updated} existing records updated · No duplicate appends</p><Link to="/dashboard" className="text-link">See your updated dashboard <ArrowRight size={16}/></Link></div></div>}
 {!parsed?<button className="upload-zone" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void chooseFile(e.dataTransfer.files[0]);}}><span className="upload-icon"><UploadCloud size={28}/></span><strong>Drop your CSV here, or browse files</strong><span>Original source IDs keep repeat imports safe.</span><small>Dates: YYYY-MM-DD · Amounts: dollars with up to 2 decimals</small></button>:<><div className="file-summary"><FileSpreadsheet size={20}/><strong>{filename}</strong><span>{parsed.rows.length} rows · {parsed.headers.length} columns</span><button className="text-link" onClick={()=>{setParsed(null);setCsv('');}}>Choose another file</button></div><div className="mapping-grid">{fields.map(f=><label key={f}><span>{labels[f]}{['source_id','occurred_at',...(['transactions','appointments','opportunities'].includes(kind)?['status']:[]),...(['transactions','expenses','ad_spend','commissions','opportunities'].includes(kind)?['amount']:[])].includes(f)&&<b> *</b>}</span><select value={mapping[f]||''} onChange={e=>setMapping({...mapping,[f]:e.target.value})}><option value="">Not mapped</option>{parsed.headers.map(h=><option key={h}>{h}</option>)}</select></label>)}</div><div className="notice"><ShieldIcon/>Suggested mappings use column names. Check them against your export before importing. A source ID must stay the same when you re-export.</div>{preview&&preview.errors.length>0&&<div className="notice warning"><div><strong>{preview.errors.length} rows need attention. Nothing will be imported until they’re fixed.</strong><ul>{preview.errors.slice(0,8).map(e=><li key={e.row}>Row {e.row}: {e.message}</li>)}</ul></div></div>}{!!preview?.repeated&&<div className="notice warning">{preview.repeated} repeated IDs within this file. The last row for each source ID will be used.</div>}<h3 className="preview-title">Record preview <span>First 5 valid rows</span></h3><RecordTable rows={preview?.records.slice(0,5)||[]}/><div className="import-actions"><span>Re-importing a file updates records with the same source ID.</span><button className="button dark" onClick={()=>void save()} disabled={busy||!preview?.records.length||!!preview?.errors.length}>{busy?'Importing…':'Import '+(preview?.records.length||0)+' records'}<ArrowRight size={17}/></button></div></>}
 <input className="sr-only" tabIndex={-1} ref={input} type="file" accept=".csv,text/csv" onChange={e=>{void chooseFile(e.target.files?.[0]);e.target.value='';}}/></section><div className="notice"><div><strong>Exports are available now. Automatic sync is a separate setup.</strong><p>Start with full exports, then re-import updates using the same source IDs. Native GHL and Stripe webhook connections are not active in this version.</p></div></div></Layout>;
}
function ShieldIcon(){return <CheckCircle2 size={18}/>;}

