import {useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import {Search,GitMerge,ArrowRight,CheckCircle2,Undo2} from 'lucide-react';
import Layout from '../components/Layout/Layout';
import {useWorkspace,type SavedRecord} from '../lib/useWorkspace';
import {formatExact} from '../lib/engine';
import {post} from '../lib/api';
import Modal from '../components/Workspace/Modal';
import {LoadState} from '../components/Workspace/Controls';
export default function Reconciliation(){
 const{data,error,loading,refresh}=useWorkspace(),[params]=useSearchParams(),[tab,setTab]=useState(params.get('tab')==='failed'?'failed':'unmatched'),[search,setSearch]=useState(''),[selected,setSelected]=useState<SavedRecord|null>(null),[contactId,setContact]=useState(''),[contactSearch,setContactSearch]=useState(''),[action,setAction]=useState('match'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[writeError,setWriteError]=useState('');
 const active=data?.records.filter(r=>!r.excluded)||[],tx=active.filter(r=>r.kind==='transactions');
 const candidates=tx.filter(r=>tx.some(other=>other.id!==r.id&&other.source!==r.source&&r.amount===other.amount&&r.occurred_at===other.occurred_at&&r.status===other.status&&((r.contact_id&&r.contact_id===other.contact_id)||(r.email&&r.email===other.email))));
 const groups:{[key:string]:SavedRecord[]}={unmatched:tx.filter(r=>!r.contact_id),duplicates:candidates,failed:tx.filter(r=>r.status==='failed'),excluded:data?.records.filter(r=>r.excluded)||[]};
 const rows=groups[tab].filter(r=>(r.name+' '+r.email+' '+r.source_id+' '+r.source).toLowerCase().includes(search.toLowerCase()));
 const contacts=active.filter(r=>r.kind==='contacts'&&(r.name+' '+r.email).toLowerCase().includes(contactSearch.toLowerCase()));
 const open=(row:SavedRecord,which:string)=>{setSelected(row);setAction(which);setContact('');setReason('');setWriteError('');};
 const save=async()=>{if(!selected)return;setBusy(true);setWriteError('');try{await post('/reconcile',{id:selected.id,action,contactId,reason});setSelected(null);setMessage(action==='match'?'Customer matched. Attribution will use this contact.':action==='exclude'?'Record excluded from every metric. You can restore it at any time.':'Record restored to your metrics.');await refresh();}catch(e){setWriteError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}};
 return <Layout title="Reconciliation" subtitle="Keep the money visible. Make the uncertainty explicit."><LoadState loading={loading} error={error} retry={()=>void refresh()}/>{message&&<div className="notice success" role="status"><CheckCircle2 size={18}/>{message}</div>}<div className="reconcile-banner"><span className="reconcile-symbol"><GitMerge size={25}/></span><div><h2>Every exception deserves an answer.</h2><p>Unmatched payments still count toward collected cash. Match them to a customer to complete attribution.</p></div></div><div className="reconcile-tabs">{[['unmatched','Unmatched'],['duplicates','Possible duplicates'],['failed','Failed payments'],['excluded','Excluded']].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}<span>{groups[key].length}</span></button>)}</div><section className="panel"><div className="panel-heading"><div><h2>{({unmatched:'Give every payment a customer.',duplicates:'Confirm before you exclude.',failed:'Revenue that hasn’t landed.',excluded:'Nothing disappears without a record.'} as Record<string,string>)[tab]}</h2><p>{tab==='duplicates'?'Same amount, date, customer, and status across different sources. These are review candidates, not proven duplicates.':tab==='failed'?'Check the processor before retrying a payment. This app does not charge customers.':tab==='excluded'?'Excluded records remain available for audit and can be restored.':'Email matches are suggestions. Manual matches are recorded in the audit log.'}</p></div><label className="search-field"><Search size={16}/><input aria-label="Search reconciliation records" placeholder="Search records…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Customer / record</th><th>Source</th><th>Date</th><th className="number">Amount</th><th>Issue</th><th/></tr></thead><tbody>{rows.slice(0,100).map(r=><tr key={r.id}><td><strong>{r.name||'Unknown customer'}</strong><small>{r.email||r.source_id}</small></td><td><span className="badge neutral">{r.source}</span></td><td>{r.occurred_at}</td><td className="number"><strong>{formatExact(r.amount)}</strong></td><td><span className="badge warning">{tab==='unmatched'?r.data.match_confidence||'Unmatched':tab==='duplicates'?'Check both sources':tab==='failed'?'Failed':'Excluded'}</span></td><td><button className="row-action" onClick={()=>open(r,tab==='excluded'?'restore':tab==='unmatched'?'match':tab==='duplicates'?'exclude':'inspect')}>{tab==='excluded'?<><Undo2 size={14}/>Restore</>:<>Review <ArrowRight size={14}/></>}</button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty-state"><CheckCircle2 size={34}/><h3>{search?'No matching records.':'You’re clear here.'}</h3><p>{search?'Try a different search.':'No '+tab.replace('_',' ')+' records in this workspace.'}</p></div>}</div></section>
 {selected&&<Modal title={action==='match'?'Match a customer':action==='exclude'?'Exclude a duplicate':action==='restore'?'Restore this record':'Payment details'} onClose={()=>setSelected(null)}><div className="modal-body"><div className="record-summary"><strong>{formatExact(selected.amount)}</strong><span>{selected.source} · {selected.source_id}</span><p>{selected.name} · {selected.occurred_at}</p></div>{action==='match'&&<><label className="field-label">Find a contact<input autoFocus value={contactSearch} onChange={e=>setContactSearch(e.target.value)} placeholder="Name or email"/></label><label className="field-label">Match this payment to<select value={contactId} onChange={e=>setContact(e.target.value)}><option value="">Choose a contact</option>{contacts.map(c=><option key={c.id} value={c.id}>{c.name||c.email} — {c.email||c.source_id}</option>)}</select></label><p className="muted">The original payment is preserved. This decision overrides automatic email matching.</p></>}{action==='exclude'&&<><p>Exclude only after comparing both source records. This removes the selected record from all metrics and keeps its history.</p><label className="field-label">Reason<textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="For example: duplicate of Stripe payment pay_123" minLength={3}/></label></>}{action==='restore'&&<p>This record will count toward metrics again.</p>}{action==='inspect'&&<dl className="details-grid">{Object.entries({...selected,...selected.data}).filter(([k])=>!['data','id'].includes(k)).map(([k,v])=><div key={k}><dt>{k.replace(/_/g,' ')}</dt><dd>{String(v)}</dd></div>)}</dl>}
 {writeError&&<p className="notice warning" role="alert">{writeError}</p>}{action!=='inspect'&&<button className="button dark" onClick={()=>void save()} disabled={busy||(action==='match'&&!contactId)||(action==='exclude'&&reason.trim().length<3)}>{busy?'Saving…':action==='match'?'Confirm match':action==='exclude'?'Exclude record':'Restore record'}<ArrowRight size={16}/></button>}</div></Modal>}</Layout>
}
