import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight} from 'lucide-react';
import Layout from '../components/Layout/Layout';
import {submissionService,type DatabaseSubmission} from '../lib/supabase';
import {useAuth} from '../context/AuthContext';
import {dateRange} from '../lib/useWorkspace';
const definitions:Record<string,[string,string][]>={'closer':[['discoveryCallsTaken','Discovery calls taken'],['offersMade','Offers made'],['totalCloses','Closes'],['cashCollected','Cash reported ($)']],'phone-setter':[['totalDials','Outbound dials'],['meaningfulConversations','Meaningful conversations'],['totalSets','Calls booked'],['closes','Closes']],'dm-setter':[['outboundIGDMsSent','Outbound DMs'],['outboundIGDMsReplied','Replies'],['totalCallsBooked','Calls booked'],['setsClosed','Closes']]};
export default function TeamPerformance(){const{mode}=useAuth();const[role,setRole]=useState('closer'),[period,setPeriod]=useState('30'),[rows,setRows]=useState<DatabaseSubmission[]>([]),[error,setError]=useState('');
 useEffect(()=>{submissionService.getAll().then(setRows).catch(e=>setError(e.message));},[mode]);const range=dateRange(period),filtered=rows.filter(r=>r.submission_type===role&&r.submission_date>=range.from&&r.submission_date<=range.to);
 return <Layout title="Sales team" subtitle="Human-reported activity, separated from processor-verified revenue."><div className="view-tabs"><Link to="/dashboard">Executive view</Link><span className="active">Sales team</span></div><div className="filter-bar"><div className="filter-inputs"><select aria-label="Sales role" value={role} onChange={e=>setRole(e.target.value)}><option value="closer">Closer</option><option value="phone-setter">Phone setter</option><option value="dm-setter">DM setter</option></select><select aria-label="Team date range" value={period} onChange={e=>setPeriod(e.target.value)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select></div><Link className="button dark" to="/eod-form">Daily check-in <ArrowRight size={16}/></Link></div>{error&&<p role="alert" className="notice warning">{error}</p>}<div className="metric-grid">{definitions[role].map(([key,label])=><div className="metric-tile" key={key}><span className="metric-label">{label}</span><strong>{filtered.reduce((n,r)=>n+Number(r.data[key]||0),0).toLocaleString()}</strong><span className="metric-note">From {filtered.length} daily check-ins</span></div>)}</div><section className="panel"><div className="panel-heading"><h2>Activity by team member</h2><span className="badge neutral">Self-reported</span></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Team member</th><th>Check-ins</th>{definitions[role].map(([k,l])=><th key={k}>{l}</th>)}</tr></thead><tbody>{[...new Set(filtered.map(r=>r.user_id))].map(id=>{const entries=filtered.filter(r=>r.user_id===id);return <tr key={id}><td><strong>{entries[0]?.users?.name||'Team member'}</strong></td><td>{entries.length}</td>{definitions[role].map(([k])=><td key={k}>{entries.reduce((n,r)=>n+Number(r.data[k]||0),0).toLocaleString()}</td>)}</tr>})}</tbody></table>{!filtered.length&&<div className="empty-state"><h3>No check-ins in this period.</h3><p>Add team members to the roster, then submit a daily check-in.</p><Link className="button dark" to="/eod-form">Add a check-in</Link></div>}</div></section><div className="notice">Manual sales reports are never added to imported transactions. This avoids counting the same payment twice.</div><div className="inline-links"><Link to="/admin/all-submissions">All submissions</Link><Link to="/admin/eod-compliance">Check-in compliance</Link><Link to="/team-goals">Team goals</Link></div></Layout>;
}