import { sqliteTable, text, integer, uniqueIndex, index } from 'drizzle-orm/sqlite-core';
export const workspaces=sqliteTable('workspaces',{id:text('id').primaryKey(),owner:text('owner').notNull(),mode:text('mode').notNull(),settings:text('settings').notNull().default('{}'),createdAt:text('created_at').notNull()});
export const records=sqliteTable('records',{id:text('id').primaryKey(),orgId:text('org_id').notNull(),kind:text('kind').notNull(),source:text('source').notNull(),sourceId:text('source_id').notNull(),occurredAt:text('occurred_at').notNull(),payload:text('payload').notNull(),excluded:integer('excluded').notNull().default(0),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('records_natural_key').on(t.orgId,t.kind,t.source,t.sourceId),index('records_org_date').on(t.orgId,t.occurredAt)]);
export const ingestRuns=sqliteTable('ingest_runs',{id:text('id').primaryKey(),orgId:text('org_id').notNull(),payload:text('payload').notNull(),createdAt:text('created_at').notNull()},t=>[index('runs_org_time').on(t.orgId,t.createdAt)]);
export const roster=sqliteTable('roster',{id:text('id').notNull(),orgId:text('org_id').notNull(),payload:text('payload').notNull()},t=>[uniqueIndex('roster_org_id').on(t.orgId,t.id)]);
export const reports=sqliteTable('daily_reports',{id:text('id').primaryKey(),orgId:text('org_id').notNull(),userId:text('user_id').notNull(),date:text('date').notNull(),payload:text('payload').notNull()},t=>[uniqueIndex('reports_org_user_date').on(t.orgId,t.userId,t.date)]);
export const goals=sqliteTable('team_goals',{id:text('id').primaryKey(),orgId:text('org_id').notNull(),userId:text('user_id').notNull(),month:text('month').notNull(),payload:text('payload').notNull()},t=>[uniqueIndex('goals_org_user_month').on(t.orgId,t.userId,t.month)]);
export const audit=sqliteTable('audit_log',{id:text('id').primaryKey(),orgId:text('org_id').notNull(),actorId:text('actor_id').notNull(),action:text('action').notNull(),target:text('target').notNull(),detail:text('detail').notNull(),createdAt:text('created_at').notNull()},t=>[index('audit_org_time').on(t.orgId,t.createdAt)]);
export const inquiries=sqliteTable('inquiries',{id:text('id').primaryKey(),email:text('email').notNull(),payload:text('payload').notNull(),createdAt:text('created_at').notNull()},t=>[uniqueIndex('inquiries_email').on(t.email)]);
