import {useState,useEffect} from 'react';
import {Save,CheckCircle2,ShieldCheck} from 'lucide-react';
import Layout from '../../components/Layout/Layout';
import {api,post} from '../../lib/api';
import {useAuth} from '../../context/AuthContext';
export default function Settings(){const{mode}=useAuth();const[settings,setSettings]=useState({companyName:'',currency:'USD',monthlyTarget:10000000,showBenchmark:70}),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{api('/settings').then(setSettings).catch(e=>setError(e.message));},[mode]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');setMessage('');try{await post('/settings',settings);setMessage('Workspace settings saved.');window.dispatchEvent(new Event('nbs-refresh'));}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}};
 return <Layout title="Settings" subtitle="A few meaningful defaults for your business."><section className="panel settings-panel"><div className="panel-heading"><div><span className="eyebrow">WORKSPACE DEFAULTS</span><h2>Make the numbers yours.</h2></div></div><form className="settings-form" onSubmit={save}><label className="field-label">Business name<input required maxLength={80} value={settings.companyName} onChange={e=>setSettings({...settings,companyName:e.target.value})}/></label><label className="field-label">Monthly cash target (USD)<input type="number" min="0" step=".01" required value={settings.monthlyTarget/100} onChange={e=>setSettings({...settings,monthlyTarget:Math.round(Number(e.target.value)*100)})}/></label><label className="field-label">Show-rate benchmark (%)<input type="number" min="0" max="100" step=".1" required value={settings.showBenchmark} onChange={e=>setSettings({...settings,showBenchmark:Number(e.target.value)})}/></label><div className="notice"><ShieldCheck size={20}/><div><strong>Private access is managed by the app host.</strong><p>Team roster entries are reporting profiles, not login invitations. This version uses USD and date-only reporting. No email reminders, password policies, or billing controls are simulated here.</p></div></div>{message&&<p className="notice success" role="status"><CheckCircle2 size={18}/>{message}</p>}{error&&<p className="notice warning" role="alert">{error}</p>}<button className="button dark" disabled={busy}><Save size={16}/>{busy?'Saving…':'Save settings'}</button></form></section></Layout>;
}