import {useEffect,useState} from 'react';
import {Plus,Users as UsersIcon,Edit2,Trash2} from 'lucide-react';
import Layout from '../../components/Layout/Layout';
import Modal from '../../components/Workspace/Modal';
import {userService,type DatabaseUser} from '../../lib/supabase';
import {useAuth} from '../../context/AuthContext';
export default function Users(){const{mode,user}=useAuth(),[people,setPeople]=useState<DatabaseUser[]>([]),[edit,setEdit]=useState<{id?:string;name:string;email:string;role:DatabaseUser['role']}|null>(null),[deleting,setDeleting]=useState<DatabaseUser|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const refresh=()=>userService.getAll().then(setPeople).catch(e=>setError(e.message));useEffect(()=>{void refresh();},[mode]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!edit)return;setBusy(true);setError('');try{if(edit.id)await userService.update(edit.id,edit);else await userService.create(edit);setEdit(null);await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}};
 const remove=async()=>{if(!deleting)return;setBusy(true);setError('');try{await userService.delete(deleting.id);setDeleting(null);await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not remove.');}finally{setBusy(false);}};
 return <Layout title="Team roster" subtitle="The people behind your activity reports."><div className="notice"><UsersIcon size={20}/><div><strong>Reporting profiles, with clear boundaries.</strong><p>These profiles organize daily check-ins and goals. Adding someone here does not invite them or grant access to your private workspace.</p></div></div><div className="section-heading"><h2>{people.length} team profiles</h2><button className="button dark" onClick={()=>{setError('');setEdit({name:'',email:'',role:'closer'})}}><Plus size={16}/>Add team member</button></div>{error&&!edit&&!deleting&&<p role="alert" className="notice warning">{error}</p>}<section className="panel"><div className="table-scroll"><table className="data-table"><thead><tr><th>Name</th><th>Email</th><th>Reporting role</th><th/></tr></thead><tbody>{people.map(p=><tr key={p.id}><td><strong>{p.name}</strong>{p.id===user?.id&&<small>Workspace owner</small>}</td><td>{p.email||'Managed by app host'}</td><td><span className="badge neutral">{p.role.replace('-',' ')}</span></td><td><div className="flex gap-4 justify-end"><button aria-label={'Edit '+p.name} onClick={()=>{setError('');setEdit(p)}}><Edit2 size={16}/></button>{p.id!==user?.id&&<button aria-label={'Remove '+p.name} onClick={()=>{setError('');setDeleting(p)}}><Trash2 size={16}/></button>}</div></td></tr>)}</tbody></table></div></section>{edit&&<Modal title={edit.id?'Edit team profile':'Add a team member'} onClose={()=>setEdit(null)}><form onSubmit={save} className="modal-body"><label className="field-label">Full name<input required maxLength={100} autoFocus value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label className="field-label">Email<input required type="email" value={edit.email} onChange={e=>setEdit({...edit,email:e.target.value})}/></label><label className="field-label">Reporting role<select value={edit.role} disabled={edit.id===user?.id} onChange={e=>setEdit({...edit,role:e.target.value as DatabaseUser['role']})}><option value="closer">Closer</option><option value="dm-setter">DM setter</option><option value="phone-setter">Phone setter</option><option value="admin">Executive</option></select></label>{error&&<p role="alert" className="notice warning">{error}</p>}<button className="button dark" disabled={busy}>{busy?'Saving…':'Save profile'}</button></form></Modal>}{deleting&&<Modal title="Remove team profile?" onClose={()=>setDeleting(null)}><div className="modal-body"><p>Remove {deleting.name} from the roster? Their historical check-ins and goals remain saved.</p>{error&&<p role="alert" className="notice warning">{error}</p>}<button className="button dark" onClick={()=>void remove()} disabled={busy}>{busy?'Removing…':'Remove profile'}</button></div></Modal>}</Layout>
}